<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;

class HomeRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'project_name' => 'nullable',
            'project_status' => 'integer',
            'user_name' => 'nullable',
            'sort' => 'integer',
        ];
    }

    public function validated($key = null, $default = null)
    {
        return parent::validated($key, $default); // TODO: Change the autogenerated stub
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
